"""5 step functions composing the /ship pipeline (SKILL-14, D-05, Plan 05-04).

Pure-function stateless steps — no state.json, no file_locked around pipeline
state (Pitfall 4 enforcement). Each step returns a :class:`StepResult` whose
``success`` bool drives the handler's halt-or-continue decision.

Steps (in pipeline order):

1. :func:`sync_main`      — ``git fetch origin main`` + ``git merge origin/main``
2. :func:`run_tests`      — language-aware test runner; bootstraps smoke test + Q-artifact if no tests
3. :func:`audit_coverage` — coverage tool dispatch + threshold compare (D-15 binary-file safe)
4. :func:`push`           — ``git push -u origin <branch>``
5. :func:`open_pr`        — ``gh pr create`` (missing gh → :class:`SkillUnavailable`)

All external calls go through :func:`invoke_native_cli` which hard-codes
``shell=False`` (T-05-04-01 mitigation: branch names / titles / bodies are
argv-literal, never shell-spliced).
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from clawteam.plugins.skill_errors import SkillUnavailable
from clawteam.spawn.invoke import invoke_native_cli


_GH_INSTALL_HINT = "apt install gh | brew install gh | winget install GitHub.cli"


@dataclass
class StepResult:
    """Outcome of a single /ship step.

    ``success`` drives the handler's halt-or-continue decision; ``details`` is
    a free-form dict merged into the ship-notes.md artifact (and used by
    downstream test assertions).
    """

    success: bool
    details: dict[str, Any] = field(default_factory=dict)


# ── Bootstrap smoke-test templates (D-06 — written when no tests detected) ──

_SMOKE_PY_TEMPLATE = '''"""Bootstrap smoke test — auto-generated by /ship (D-06).

TODO: flesh out this smoke test with real assertions before re-running /ship.
"""


def test_smoke():
    # Trivial truthy check — replace with a real import + assertion proving
    # the project entry point loads.
    assert True
'''

_SMOKE_TS_TEMPLATE = '''// Bootstrap smoke test — auto-generated by /ship (D-06).
// TODO: flesh out this smoke test with real assertions before re-running /ship.
import { test, expect } from "vitest";

test("smoke test", () => {
  expect(true).toBe(true);
});
'''

_QUESTION_ARTIFACT_BODY = (
    "---\n"
    "question_id: 001\n"
    "priority: blocking\n"
    "---\n\n"
    "### Flesh out bootstrapped smoke test\n\n"
    "No test suite detected on this branch. /ship wrote a TODO smoke test at "
    "`tests/test_smoke.py` (python) or `tests/smoke.test.ts` (node).\n\n"
    "Please replace the trivial assertion with a real import + check that "
    "proves the project entry point loads. Then re-run /ship.\n"
)


# ── Language / test detection ───────────────────────────────────────────


def _detect_language(cwd: Path) -> str:
    """Return 'python' | 'node' | 'go' | 'rust' | 'unknown' per D-06 signals."""
    if (cwd / "pyproject.toml").exists() or (cwd / "setup.py").exists():
        return "python"
    if (cwd / "package.json").exists():
        return "node"
    if (cwd / "go.mod").exists():
        return "go"
    if (cwd / "Cargo.toml").exists():
        return "rust"
    return "unknown"


def _has_tests(cwd: Path, language: str) -> bool:
    """Return True iff the workspace already has tests for the detected language."""
    if language == "python":
        return (
            any(cwd.glob("tests/test_*.py"))
            or any(cwd.glob("test_*.py"))
            or any(cwd.glob("tests/**/test_*.py"))
        )
    if language == "node":
        if (cwd / "tests").is_dir() and any(
            (cwd / "tests").glob("*.test.*")
        ):
            return True
        if (cwd / "__tests__").is_dir():
            return True
        if any(cwd.glob("*.test.ts")) or any(cwd.glob("**/*.test.ts")):
            return True
        if any(cwd.glob("*.test.js")) or any(cwd.glob("**/*.test.js")):
            return True
        return False
    if language == "go":
        return any(cwd.glob("**/*_test.go"))
    if language == "rust":
        return (cwd / "tests").is_dir()
    return False


def _bootstrap_tests(cwd: Path, language: str, sprint_dir: Path) -> None:
    """Write a language-appropriate smoke test + a blocking question artifact.

    Side-effects:
      - ``<cwd>/tests/test_smoke.py`` or ``<cwd>/tests/smoke.test.ts`` created.
      - ``<sprint_dir>/questions/001_flesh_out_smoke_test.md`` created (D-06 human nudge).
    """
    tests_dir = cwd / "tests"
    tests_dir.mkdir(exist_ok=True)
    if language == "python":
        (tests_dir / "test_smoke.py").write_text(_SMOKE_PY_TEMPLATE)
    elif language == "node":
        (tests_dir / "smoke.test.ts").write_text(_SMOKE_TS_TEMPLATE)

    questions_dir = sprint_dir / "questions"
    questions_dir.mkdir(parents=True, exist_ok=True)
    (questions_dir / "001_flesh_out_smoke_test.md").write_text(
        _QUESTION_ARTIFACT_BODY
    )


# ── Step 1: sync_main ──────────────────────────────────────────────────


def sync_main(cwd: Path, branch: str, *, timeout: float = 120.0) -> StepResult:
    """Fast-forward/merge origin/main into current branch.

    Returns ``success=False`` + ``details['conflict']=True`` on merge conflict;
    does NOT raise, does NOT swallow stderr.
    """
    fetch = invoke_native_cli(
        ["git", "fetch", "origin", "main"], cwd=cwd, timeout=timeout,
    )
    if fetch.returncode != 0:
        return StepResult(
            False, {"error": "fetch_failed", "stderr": fetch.stderr},
        )
    merge = invoke_native_cli(
        ["git", "merge", "origin/main", "--no-edit"],
        cwd=cwd,
        timeout=timeout,
    )
    if merge.returncode != 0:
        return StepResult(
            False,
            {"conflict": True, "stderr": merge.stderr, "branch": branch},
        )
    return StepResult(True, {"synced_onto": "main", "branch": branch})


# ── Step 2: run_tests ──────────────────────────────────────────────────


def run_tests(
    cwd: Path,
    sprint_dir: Path,
    *,
    timeout: float = 600.0,
) -> StepResult:
    """Detect language, bootstrap if no tests, else run language-native test cmd.

    Bootstrap halts with ``success=False`` + ``details['bootstrapped']=True``
    so the caller re-runs /ship after fleshing out the smoke test (D-06).
    """
    language = _detect_language(cwd)
    if language == "unknown":
        return StepResult(False, {"error": "unknown_language"})
    if not _has_tests(cwd, language):
        _bootstrap_tests(cwd, language, sprint_dir)
        return StepResult(
            False,
            {
                "bootstrapped": True,
                "language": language,
                "hint": (
                    "question emitted; flesh out smoke test and re-run /ship"
                ),
            },
        )

    if language == "python":
        cmd = ["pytest", "-x", "--tb=short"]
    elif language == "node":
        # vitest is the Phase-5 default; jest detection is v1.x.
        cmd = ["npx", "vitest", "run"]
    elif language == "go":
        cmd = ["go", "test", "./..."]
    elif language == "rust":
        cmd = ["cargo", "test"]
    else:
        return StepResult(False, {"error": "unknown_language"})

    result = invoke_native_cli(cmd, cwd=cwd, timeout=timeout)
    return StepResult(
        result.returncode == 0,
        {
            "language": language,
            "exit_code": result.returncode,
            "stderr": result.stderr[:500] if result.stderr else "",
        },
    )


# ── Step 3: audit_coverage ─────────────────────────────────────────────


def _parse_python_coverage(cov_file: Path) -> StepResult | float:
    """Return a float 0..1 on success, or a failed StepResult on parse error."""
    try:
        data = json.loads(cov_file.read_text())
    except (ValueError, OSError) as exc:
        return StepResult(False, {"error": f"parse_failed: {exc}"})
    # totals.percent_covered is the canonical pytest-cov JSON field. Use .get
    # chain so malformed coverage.json (missing totals, missing key) does
    # NOT crash; T-05-04-02 mitigation. Extra keys like `not_coverable` are
    # naturally ignored by the .get chain — D-15 binary-file adversarial.
    totals = data.get("totals") or {}
    raw_pct = totals.get("percent_covered")
    if raw_pct is None:
        return StepResult(False, {"error": "missing_totals.percent_covered"})
    try:
        return float(raw_pct) / 100.0
    except (TypeError, ValueError) as exc:
        return StepResult(False, {"error": f"percent_not_numeric: {exc}"})


def _parse_node_coverage(cov_file: Path) -> StepResult | float:
    try:
        data = json.loads(cov_file.read_text())
        return float(data["total"]["lines"]["pct"]) / 100.0
    except (KeyError, TypeError, ValueError, OSError) as exc:
        return StepResult(False, {"error": f"parse_failed: {exc}"})


def audit_coverage(
    cwd: Path,
    threshold: float,
    *,
    timeout: float = 600.0,
) -> StepResult:
    """Run language-appropriate coverage tool; compare to threshold.

    Threshold is interpreted as a fraction 0..1 (default 0.5 = 50%). Non
    python/node languages skip the deep integration in v1 — they succeed
    with ``coverage=None`` so /ship can still ship; proper go/rust coverage
    is a v1.x target.
    """
    language = _detect_language(cwd)
    if language == "python":
        invoke_native_cli(
            [
                "pytest",
                "--cov",
                "--cov-report=json",
                "--cov-report=term",
                "--tb=no",
                "-q",
            ],
            cwd=cwd,
            timeout=timeout,
        )
        cov_file = cwd / "coverage.json"
        if not cov_file.exists():
            return StepResult(
                False, {"error": "coverage_file_missing", "language": "python"},
            )
        parsed = _parse_python_coverage(cov_file)
        if isinstance(parsed, StepResult):
            return parsed
        return StepResult(
            parsed >= threshold,
            {
                "coverage": round(parsed, 3),
                "threshold": threshold,
                "language": "python",
            },
        )
    if language == "node":
        invoke_native_cli(
            ["npx", "c8", "--reporter=json-summary", "npx", "vitest", "run"],
            cwd=cwd,
            timeout=timeout,
        )
        cov_file = cwd / "coverage" / "coverage-summary.json"
        if not cov_file.exists():
            return StepResult(
                False, {"error": "coverage_file_missing", "language": "node"},
            )
        parsed = _parse_node_coverage(cov_file)
        if isinstance(parsed, StepResult):
            return parsed
        return StepResult(
            parsed >= threshold,
            {
                "coverage": round(parsed, 3),
                "threshold": threshold,
                "language": "node",
            },
        )
    # go / rust / unknown: don't block the pipeline on absent v1 integration.
    return StepResult(
        True,
        {
            "coverage": None,
            "threshold": threshold,
            "language": language,
            "note": "coverage audit skipped for non-python/node",
        },
    )


# ── Step 4: push ───────────────────────────────────────────────────────


def push(cwd: Path, branch: str, *, timeout: float = 120.0) -> StepResult:
    """Push ``branch`` to ``origin`` with ``-u`` (sets upstream)."""
    result = invoke_native_cli(
        ["git", "push", "-u", "origin", branch], cwd=cwd, timeout=timeout,
    )
    return StepResult(
        result.returncode == 0,
        {
            "branch": branch,
            "exit_code": result.returncode,
            "stderr": result.stderr[:500] if result.stderr else "",
        },
    )


# ── Step 5: open_pr ─────────────────────────────────────────────────────


def open_pr(
    cwd: Path,
    title: str,
    body: str,
    *,
    timeout: float = 60.0,
) -> StepResult:
    """Open a PR via ``gh pr create``; raise :class:`SkillUnavailable` if gh missing.

    ``title`` / ``body`` are passed as argv elements (shell=False enforced by
    :func:`invoke_native_cli`) so shell metachars in either are safe
    (T-05-04-01 mitigation).
    """
    if shutil.which("gh") is None:
        raise SkillUnavailable(
            skill="/ship",
            binary="gh",
            install_hint=_GH_INSTALL_HINT,
        )
    result = invoke_native_cli(
        ["gh", "pr", "create", "--title", title, "--body", body],
        cwd=cwd,
        timeout=timeout,
    )
    if result.returncode != 0:
        return StepResult(
            False,
            {
                "error": "gh_failed",
                "exit_code": result.returncode,
                "stderr": (result.stderr or "")[:500],
            },
        )
    pr_url = ""
    for line in reversed(result.stdout.splitlines()):
        line = line.strip()
        if line.startswith("http"):
            pr_url = line
            break
    return StepResult(
        bool(pr_url),
        {
            "pr_url": pr_url or None,
            "stdout": (result.stdout or "")[:500],
        },
    )
